/* This file is generated by BUSMASTER */
/* VERSION [1.1] */
/* BUSMASTER VERSION [1.7.0] */
/* PROTOCOL [CAN] */

/* Start BUSMASTER include header */
#include <Windows.h>
#include <CANIncludes.h>

/* End BUSMASTER include header */


/* Start BUSMASTER global variable */
unsigned int counter_100ms = 0;

unsigned char blinker_left = 0;
unsigned char blinker_right = 0;
unsigned char temp = 0xDE;
unsigned char backlight = 0xF;
unsigned char clock_h = 0;
unsigned char clock_m = 0;

const unsigned char lut_o0_counter[]=
{
	0x00,
	0x40,
	0x80,
	0xC0
};

const unsigned char lut_1D604008[][7]=
{
	{0x05,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF},
	{0x15,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF},
	{0x05,0xFF,0xFF,0xFF,0xFF,0x50,0xFF},
	{0x15,0x00,0x70,0x00,0x03,0x04,0x42},
	{0x05,0x00,0x00,0x23,0x31,0x73,0x68},
	{0x05,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF},
	{0x15,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF}
};

#if 1
const unsigned char lut_1093F7FC[][9]=
{
	{ 1,0x01,0x00,0x0F,0xB0,0x44,0x59,0x00,0x86},
	{ 2,0x02,0x03,0xFE,0x00,0x38,0x00,0x00,0x00},
	{ 5,0x01,0x00,0x0F,0xB0,0x44,0x4F,0xFF,0x79},
	{ 6,0x05,0x00,0x00,0x00,0x00,0x00,0x07,0xAD},
	{ 8,0x11,0x4D,0x43,0x35,0x38,0x35,0x31,0x43},
	{ 9,0x01,0x00,0x0F,0xB0,0x44,0x59,0x00,0x86},
	{10,0x02,0x03,0xFE,0x00,0x38,0x00,0x00,0x00},
	{13,0x01,0x00,0x0F,0xB0,0x44,0x4F,0xFF,0x79},
	{16,0x12,0x4A,0x31,0x33,0x32,0x30,0x30,0x39},
	{17,0x01,0x00,0x0F,0xB0,0x44,0x59,0x00,0x86},
	{18,0x02,0x03,0xFE,0x00,0x38,0x00,0x00,0x00},
	{20,0x10,0x00,0x00,0x00,0x00,0x59,0x56,0x31}
};
#else

const unsigned char lut_1093F7FC[][9]=
{
	{ 1,0x01,0x00,0x0F,0xB0,0x44,0x59,0x00,0x86},
	{ 2,0x02,0x03,0xFE,0x00,0x38,0x00,0x00,0x00},
	{ 5,0x01,0x00,0x0F,0xB0,0x44,0x4F,0xFF,0x79},
	{ 6,0x05,0x00,0x00,0x00,0x00,0x00,0x07,0xAD},
	{ 8,0x11,'L','O',' ','W','O','R','L'},
	{ 9,0x01,0x00,0x0F,0xB0,0x44,0x59,0x00,0x86},
	{10,0x02,0x03,0xFE,0x00,0x38,0x00,0x00,0x00},
	{13,0x01,0x00,0x0F,0xB0,0x44,0x4F,0xFF,0x79},
	{16,0x12,'D',' ','h','e','l','l','o'},
	{17,0x01,0x00,0x0F,0xB0,0x44,0x59,0x00,0x86},
	{18,0x02,0x03,0xFE,0x00,0x38,0x00,0x00,0x00},
	{20,0x10,0x00,0x00,0x00,0x00,'H','E','L'}
};
#endif
const unsigned char lut_1163F7FC[][7]=
{
	{0x04,0x06,0x07,0x01,0x05,0x04,0x02},
	{0x01,0x05,0x01,0x03,0x01,0x02,0x02},
	{0x03,0x02,0x01,0x02,0x02,0x02,0x02},
	{0x0D,0x33,0x02,0x01,0x02,0x01,0x01},
	{0x01,0x01,0x04,0x01,0x03,0x04,0x03},
	{0x01,0x01,0x07,0x05,0x05,0x02,0x01},
	{0x02,0x03,0x00,0x02,0x01,0x01,0x01},
	{0x02,0x01,0x12,0x02,0x03,0x02,0x01},
	{0x00,0x00,0x01,0x01,0x01,0x01,0x01},
	{0x01,0x01,0x01,0x01,0x02,0x05,0x01},
	{0x01,0x01,0x01,0x01,0x04,0x01,0x03},
	{0x03,0x01,0x01,0x01,0x02,0x01,0x08},
	{0x01,0x02,0x03,0x01,0x03,0x01,0x01},
	{0x02,0x02,0x01,0x02,0x02,0x03,0x02},
	{0x01,0x03,0x01,0x01,0x01,0x02,0x02},
	{0x01,0x07,0x10,0x02,0x02,0x03,0x02},
	{0x01,0x01,0x00,0x01,0x01,0x01,0x02},
	{0x06,0x01,0x01,0x02,0x00,0x00,0x00},
	{0x00,0x00,0x00,0x00,0x00,0x00,0x00},
	{0x00,0x00,0x00,0x00,0x00,0x00,0x00}
};
/* End BUSMASTER global variable */


/* Start BUSMASTER Function Prototype  */
GCC_EXTERN void GCC_EXPORT OnError_Warning_Limit(SCAN_ERR ErrorMsg);
GCC_EXTERN void GCC_EXPORT OnDLL_Load();
GCC_EXTERN void GCC_EXPORT OnTimer_timer6_100( );
GCC_EXTERN void GCC_EXPORT OnBus_Connect();
GCC_EXTERN void GCC_EXPORT OnBus_Disconnect();
GCC_EXTERN void GCC_EXPORT OnTimer_timer1_30( );
GCC_EXTERN void GCC_EXPORT OnTimer_timer2_40( );
GCC_EXTERN void GCC_EXPORT OnTimer_timer3_50( );
GCC_EXTERN void GCC_EXPORT OnTimer_timer4_70( );
GCC_EXTERN void GCC_EXPORT OnTimer_timer5_500( );
GCC_EXTERN void GCC_EXPORT OnTimer_timer7_120( );
GCC_EXTERN void GCC_EXPORT OnTimer_timer8_150( );
GCC_EXTERN void GCC_EXPORT OnTimer_timer9_200( );
GCC_EXTERN void GCC_EXPORT OnTimer_timer10_300( );
GCC_EXTERN void GCC_EXPORT OnTimer_timer11_360( );
void Utils_cem_msg_send_30ms_021204B8(void);
void Utils_cem_msg_send_30ms_03C3F7FC(void);
void Utils_cem_msg_send_40ms_043010B8(void);
void Utils_cem_msg_send_50ms_065373BA(void);
void Utils_cem_msg_send_50ms_09C050B8(void);
void Utils_cem_msg_send_50ms_0A90F698(void);
void Utils_cem_msg_send_70ms_0E03D7F8(void);
void Utils_cem_msg_send_100ms_13F041BA(void);
void Utils_cem_msg_send_100ms_16124008(void);
void Utils_cem_msg_send_100ms_18805048(void);
void Utils_cem_msg_send_100ms_1BC00020(void);
void Utils_cem_msg_send_120ms_15B04028(void);
void Utils_cem_msg_send_120ms_16801028(void);
void Utils_cem_msg_send_150ms_1760E008(void);
void Utils_cem_msg_send_200ms_19F010FC(void);
void Utils_cem_msg_send_200ms_1A621000(void);
void Utils_cem_msg_send_300ms_1AD10068(void);
void Utils_cem_msg_send_360ms_1D604008(void);
void Utils_cem_msg_send_250ms_1163F7FC(void);
void Utils_cem_msg_send_500ms_1E30106A(void);
void Utils_cem_msg_send_500ms_1F600008(void);
GCC_EXTERN void GCC_EXPORT OnTimer_timer12_250( );
void Utils_cem_msg_send_250ms_1093F7FC(void);
GCC_EXTERN void GCC_EXPORT OnDLL_Unload();
GCC_EXTERN void GCC_EXPORT OnKey_p(unsigned char KeyValue);
GCC_EXTERN void GCC_EXPORT OnKey_o(unsigned char KeyValue);
GCC_EXTERN void GCC_EXPORT OnKey_m(unsigned char KeyValue);
GCC_EXTERN void GCC_EXPORT OnKey_h(unsigned char KeyValue);
GCC_EXTERN void GCC_EXPORT OnKey_b(unsigned char KeyValue);
GCC_EXTERN void GCC_EXPORT OnKey_t(unsigned char KeyValue);
/* End BUSMASTER Function Prototype  */

/* Start BUSMASTER generated function - OnError_Warning_Limit */
void OnError_Warning_Limit(SCAN_ERR ErrorMsg)
{
Trace("Warning Limit reached");
}/* End BUSMASTER generated function - OnError_Warning_Limit */
/* Start BUSMASTER generated function - OnDLL_Load */
void OnDLL_Load()
{
/* TODO: Define and Initialise the following variables*/

 EnableLogging();

}/* End BUSMASTER generated function - OnDLL_Load */
/* Start BUSMASTER generated function - OnTimer_timer6_100 */
void OnTimer_timer6_100( )
{
counter_100ms += 1;

Utils_cem_msg_send_100ms_13F041BA();
Utils_cem_msg_send_100ms_16124008();
Utils_cem_msg_send_100ms_18805048();
Utils_cem_msg_send_100ms_1BC00020();
}/* End BUSMASTER generated function - OnTimer_timer6_100 */
/* Start BUSMASTER generated function - OnBus_Connect */
void OnBus_Connect()
{
Trace("Bus connected");
}/* End BUSMASTER generated function - OnBus_Connect */
/* Start BUSMASTER generated function - OnBus_Disconnect */
void OnBus_Disconnect()
{
Trace("Bus Disconnected");
}/* End BUSMASTER generated function - OnBus_Disconnect */
/* Start BUSMASTER generated function - OnTimer_timer1_30 */
void OnTimer_timer1_30( )
{
Utils_cem_msg_send_30ms_021204B8();
Utils_cem_msg_send_30ms_03C3F7FC();
}/* End BUSMASTER generated function - OnTimer_timer1_30 */
/* Start BUSMASTER generated function - OnTimer_timer2_40 */
void OnTimer_timer2_40( )
{
Utils_cem_msg_send_40ms_043010B8();
}/* End BUSMASTER generated function - OnTimer_timer2_40 */
/* Start BUSMASTER generated function - OnTimer_timer3_50 */
void OnTimer_timer3_50( )
{
Utils_cem_msg_send_50ms_065373BA();
Utils_cem_msg_send_50ms_09C050B8();
Utils_cem_msg_send_50ms_0A90F698();
}/* End BUSMASTER generated function - OnTimer_timer3_50 */
/* Start BUSMASTER generated function - OnTimer_timer4_70 */
void OnTimer_timer4_70( )
{
Utils_cem_msg_send_70ms_0E03D7F8();
}/* End BUSMASTER generated function - OnTimer_timer4_70 */
/* Start BUSMASTER generated function - OnTimer_timer5_500 */
void OnTimer_timer5_500( )
{
Utils_cem_msg_send_500ms_1E30106A();
Utils_cem_msg_send_500ms_1F600008();
}/* End BUSMASTER generated function - OnTimer_timer5_500 */
/* Start BUSMASTER generated function - OnTimer_timer7_120 */
void OnTimer_timer7_120( )
{
Utils_cem_msg_send_120ms_15B04028();
Utils_cem_msg_send_120ms_16801028();
}/* End BUSMASTER generated function - OnTimer_timer7_120 */
/* Start BUSMASTER generated function - OnTimer_timer8_150 */
void OnTimer_timer8_150( )
{
Utils_cem_msg_send_150ms_1760E008();
}/* End BUSMASTER generated function - OnTimer_timer8_150 */
/* Start BUSMASTER generated function - OnTimer_timer9_200 */
void OnTimer_timer9_200( )
{
Utils_cem_msg_send_200ms_19F010FC();
Utils_cem_msg_send_200ms_1A621000();
}/* End BUSMASTER generated function - OnTimer_timer9_200 */
/* Start BUSMASTER generated function - OnTimer_timer10_300 */
void OnTimer_timer10_300( )
{
Utils_cem_msg_send_300ms_1AD10068();
}/* End BUSMASTER generated function - OnTimer_timer10_300 */
/* Start BUSMASTER generated function - OnTimer_timer11_360 */
void OnTimer_timer11_360( )
{
Utils_cem_msg_send_360ms_1D604008();
}/* End BUSMASTER generated function - OnTimer_timer11_360 */
/* Start BUSMASTER generated function - Utils_cem_msg_send_30ms_021204B8 */
void Utils_cem_msg_send_30ms_021204B8(void)
{
// Initialise message structure
STCAN_MSG sMsg;
unsigned char i = 0;

sMsg.id = 0x021204B8;   // Message ID
sMsg.isExtended = TRUE; // Standard Message type
sMsg.isRtr = FALSE;     // Not RTR type
sMsg.dlc = 8;           // Length is 8 Bytes
sMsg.data[i++] = 0x11;  // Lower 4 Bytes
sMsg.data[i++] = 0x02 | blinker_left | blinker_right;  // (0x02/0x06)
sMsg.data[i++] = 0x00;
sMsg.data[i++] = 0x00;
sMsg.data[i++] = 0x00;
sMsg.data[i++] = 0x00;
sMsg.data[i++] = 0x00;
sMsg.data[i++] = 0x00;
sMsg.cluster = 1;
SendMsg(sMsg);
}/* End BUSMASTER generated function - Utils_cem_msg_send_30ms_021204B8 */
/* Start BUSMASTER generated function - Utils_cem_msg_send_30ms_03C3F7FC */
void Utils_cem_msg_send_30ms_03C3F7FC(void)
{
// Initialise message structure
STCAN_MSG sMsg;
unsigned char i = 0;

sMsg.id = 0x03C3F7FC;   // Message ID
sMsg.isExtended = TRUE; // Standard Message type
sMsg.isRtr = FALSE;     // Not RTR type
sMsg.dlc = 8;           // Length is 8 Bytes
sMsg.data[i++] = 0xF9;  // Lower 4 Bytes
sMsg.data[i++] = 0x03;
sMsg.data[i++] = 0xB7;
sMsg.data[i++] = 0x19;
sMsg.data[i++] = 0x40;
sMsg.data[i++] = 0x27;
sMsg.data[i++] = 0x78;
sMsg.data[i++] = 0x18;
sMsg.cluster = 1;
SendMsg(sMsg);
}/* End BUSMASTER generated function - Utils_cem_msg_send_30ms_03C3F7FC */
/* Start BUSMASTER generated function - Utils_cem_msg_send_40ms_043010B8 */
void Utils_cem_msg_send_40ms_043010B8(void)
{
// Initialise message structure
STCAN_MSG sMsg;
unsigned char i = 0;

sMsg.id = 0x043010B8;   // Message ID
sMsg.isExtended = TRUE; // Standard Message type
sMsg.isRtr = FALSE;     // Not RTR type
sMsg.dlc = 8;           // Length is 8 Bytes
sMsg.data[i++] = 0x00;  // Lower 4 Bytes
sMsg.data[i++] = 0x00;
sMsg.data[i++] = 0x00;
sMsg.data[i++] = 0x00;
sMsg.data[i++] = 0x00;
sMsg.data[i++] = 0x00;
sMsg.data[i++] = 0x00;
sMsg.data[i++] = 0x00;
sMsg.cluster = 1;
SendMsg(sMsg);
}/* End BUSMASTER generated function - Utils_cem_msg_send_40ms_043010B8 */
/* Start BUSMASTER generated function - Utils_cem_msg_send_50ms_065373BA */
void Utils_cem_msg_send_50ms_065373BA(void)
{
// Initialise message structure
STCAN_MSG sMsg;
char i = 0;
static char j = 0;
if(j>=4) j=0;

sMsg.id = 0x065373BA;   // Message ID
sMsg.isExtended = TRUE; // Standard Message type
sMsg.isRtr = FALSE;     // Not RTR type
sMsg.dlc = 8;           // Length is 8 Bytes
sMsg.data[i++] = 0x04 | lut_o0_counter[j++];    // Lower 4 Bytes
sMsg.data[i++] = 0x00;
sMsg.data[i++] = 0x20;
sMsg.data[i++] = 0xEC;
sMsg.data[i++] = 0x11;
sMsg.data[i++] = 0x00;
sMsg.data[i++] = 0x00;
if(sMsg.data[0] == 0x44)
sMsg.data[i++] = 0xA0;
else
sMsg.data[i++] = 0x20;
sMsg.cluster = 1;
SendMsg(sMsg);
}/* End BUSMASTER generated function - Utils_cem_msg_send_50ms_065373BA */
/* Start BUSMASTER generated function - Utils_cem_msg_send_50ms_09C050B8 */
void Utils_cem_msg_send_50ms_09C050B8(void)
{
// Initialise message structure
STCAN_MSG sMsg;
unsigned char i = 0;

sMsg.id = 0x09C050B8;   // Message ID
sMsg.isExtended = TRUE; // Standard Message type
sMsg.isRtr = FALSE;     // Not RTR type
sMsg.dlc = 8;           // Length is 8 Bytes
sMsg.data[i++] = 0x40 | backlight;//0x68;  // Lower 4 Bytes
sMsg.data[i++] = 0x00;
sMsg.data[i++] = 0x02;
sMsg.data[i++] = 0x00;
sMsg.data[i++] = 0x00;
sMsg.data[i++] = 0x00;
sMsg.data[i++] = 0x00;
sMsg.data[i++] = 0x4C;
sMsg.cluster = 1;
SendMsg(sMsg);
}/* End BUSMASTER generated function - Utils_cem_msg_send_50ms_09C050B8 */
/* Start BUSMASTER generated function - Utils_cem_msg_send_50ms_0A90F698 */
void Utils_cem_msg_send_50ms_0A90F698(void)
{
// Initialise message structure
STCAN_MSG sMsg;
unsigned char i = 0;

sMsg.id = 0x0A90F698;   // Message ID
sMsg.isExtended = TRUE; // Standard Message type
sMsg.isRtr = FALSE;     // Not RTR type
sMsg.dlc = 8;           // Length is 8 Bytes
sMsg.data[i++] = 0xF8;  // Lower 4 Bytes
sMsg.data[i++] = 0x2B;
sMsg.data[i++] = 0x00;
sMsg.data[i++] = 0x80;
sMsg.data[i++] = 0x00;
sMsg.data[i++] = 0x00;
sMsg.data[i++] = 0x00;
sMsg.data[i++] = 0x00;
sMsg.cluster = 1;
SendMsg(sMsg);
}/* End BUSMASTER generated function - Utils_cem_msg_send_50ms_0A90F698 */
/* Start BUSMASTER generated function - Utils_cem_msg_send_70ms_0E03D7F8 */
void Utils_cem_msg_send_70ms_0E03D7F8(void)
{
// Initialise message structure
STCAN_MSG sMsg;
char i = 0;
static char j = 0;
if(j>=4) j=0;

sMsg.id = 0x0E03D7F8;   // Message ID
sMsg.isExtended = TRUE; // Standard Message type
sMsg.isRtr = FALSE;     // Not RTR type
sMsg.dlc = 8;           // Length is 8 Bytes
sMsg.data[i++] = 0x00 | lut_o0_counter[j++];    // Lower 4 Bytes
sMsg.data[i++] = 0x21;
sMsg.data[i++] = 0x00; //
sMsg.data[i++] = 0x00; //
sMsg.data[i++] = 0x05;
sMsg.data[i++] = 0x0B;
sMsg.data[i++] = 0x50;
sMsg.data[i++] = 0x00;
sMsg.cluster = 1;
SendMsg(sMsg);
}/* End BUSMASTER generated function - Utils_cem_msg_send_70ms_0E03D7F8 */
/* Start BUSMASTER generated function - Utils_cem_msg_send_100ms_13F041BA */
void Utils_cem_msg_send_100ms_13F041BA(void)
{
// Initialise message structure
STCAN_MSG sMsg;
unsigned char i = 0;

sMsg.id = 0x13F041BA;   // Message ID
sMsg.isExtended = TRUE; // Standard Message type
sMsg.isRtr = FALSE;     // Not RTR type
sMsg.dlc = 8;           // Length is 8 Bytes
sMsg.data[i++] = 0x00;  // Lower 4 Bytes
sMsg.data[i++] = 0x4E;
sMsg.data[i++] = 0x58 | clock_h;
sMsg.data[i++] = clock_m;
sMsg.data[i++] = 0x00;
sMsg.data[i++] = 0x01;
sMsg.data[i++] = 0xD4;
sMsg.data[i++] = 0xF6;
sMsg.cluster = 1;
SendMsg(sMsg);
}/* End BUSMASTER generated function - Utils_cem_msg_send_100ms_13F041BA */
/* Start BUSMASTER generated function - Utils_cem_msg_send_100ms_16124008 */
void Utils_cem_msg_send_100ms_16124008(void)
{
// Initialise message structure
STCAN_MSG sMsg;
unsigned char i = 0;

sMsg.id = 0x16124008;   // Message ID
sMsg.isExtended = TRUE; // Standard Message type
sMsg.isRtr = FALSE;     // Not RTR type
sMsg.dlc = 8;           // Length is 8 Bytes
sMsg.data[i++] = 0x00;  // Lower 4 Bytes
sMsg.data[i++] = 0x92;
sMsg.data[i++] = 0x02;
sMsg.data[i++] = 0x10;
sMsg.data[i++] = 0x00;
sMsg.data[i++] = 0x04;
sMsg.data[i++] = 0x00;
sMsg.data[i++] = 0x00;
sMsg.cluster = 1;
SendMsg(sMsg);
}/* End BUSMASTER generated function - Utils_cem_msg_send_100ms_16124008 */
/* Start BUSMASTER generated function - Utils_cem_msg_send_100ms_18805048 */
void Utils_cem_msg_send_100ms_18805048(void)
{
// Initialise message structure
STCAN_MSG sMsg;
unsigned char i = 0;

sMsg.id = 0x18805048;   // Message ID
sMsg.isExtended = TRUE; // Standard Message type
sMsg.isRtr = FALSE;     // Not RTR type
sMsg.dlc = 8;           // Length is 8 Bytes
sMsg.data[i++] = 0x00;  // Lower 4 Bytes
sMsg.data[i++] = 0x00;
sMsg.data[i++] = 0x00;
sMsg.data[i++] = 0x00;
sMsg.data[i++] = 0x00;
sMsg.data[i++] = 0x00;
sMsg.data[i++] = 0x00;
sMsg.data[i++] = 0x82;
sMsg.cluster = 1;
SendMsg(sMsg);
}/* End BUSMASTER generated function - Utils_cem_msg_send_100ms_18805048 */
/* Start BUSMASTER generated function - Utils_cem_msg_send_100ms_1BC00020 */
void Utils_cem_msg_send_100ms_1BC00020(void)
{
// Initialise message structure
STCAN_MSG sMsg;
unsigned char i = 0;

sMsg.id = 0x1BC00020;   // Message ID
sMsg.isExtended = TRUE; // Standard Message type
sMsg.isRtr = FALSE;     // Not RTR type
sMsg.dlc = 8;           // Length is 8 Bytes
sMsg.data[i++] = 0x00;  // Lower 4 Bytes
sMsg.data[i++] = 0x00;
sMsg.data[i++] = 0x00;
sMsg.data[i++] = 0x00;
sMsg.data[i++] = 0x00;
sMsg.data[i++] = 0x00;
sMsg.data[i++] = 0x00;
sMsg.data[i++] = 0x00;
sMsg.cluster = 1;
SendMsg(sMsg);
}/* End BUSMASTER generated function - Utils_cem_msg_send_100ms_1BC00020 */
/* Start BUSMASTER generated function - Utils_cem_msg_send_120ms_15B04028 */
void Utils_cem_msg_send_120ms_15B04028(void)
{
// Initialise message structure
STCAN_MSG sMsg;
unsigned char i = 0;

sMsg.id = 0x15B04028;   // Message ID
sMsg.isExtended = TRUE; // Standard Message type
sMsg.isRtr = FALSE;     // Not RTR type
sMsg.dlc = 8;           // Length is 8 Bytes
sMsg.data[i++] = 0x0F;  // Lower 4 Bytes
sMsg.data[i++] = 0x00;
sMsg.data[i++] = 0x00;
sMsg.data[i++] = 0x00;
sMsg.data[i++] = 0x00;
sMsg.data[i++] = 0x00;
sMsg.data[i++] = 0x00;
sMsg.data[i++] = 0x00;
sMsg.cluster = 1;
SendMsg(sMsg);
}/* End BUSMASTER generated function - Utils_cem_msg_send_120ms_15B04028 */
/* Start BUSMASTER generated function - Utils_cem_msg_send_120ms_16801028 */
void Utils_cem_msg_send_120ms_16801028(void)
{
// Initialise message structure
STCAN_MSG sMsg;
char i = 0;
static char j = 0;
if(j>=4) j=0;

sMsg.id = 0x16801028;   // Message ID
sMsg.isExtended = TRUE; // Standard Message type
sMsg.isRtr = FALSE;     // Not RTR type
sMsg.dlc = 8;           // Length is 8 Bytes
sMsg.data[i++] = 0x08 | lut_o0_counter[j++];    // Lower 4 Bytes
sMsg.data[i++] = 0x00;
sMsg.data[i++] = 0x50;
sMsg.data[i++] = 0x00;
sMsg.data[i++] = 0x00;
sMsg.data[i++] = 0x00;
sMsg.data[i++] = 0x00;
sMsg.data[i++] = 0x00;
sMsg.cluster = 1;
SendMsg(sMsg);
}/* End BUSMASTER generated function - Utils_cem_msg_send_120ms_16801028 */
/* Start BUSMASTER generated function - Utils_cem_msg_send_150ms_1760E008 */
void Utils_cem_msg_send_150ms_1760E008(void)
{
// Initialise message structure
STCAN_MSG sMsg;
unsigned char i = 0;

sMsg.id = 0x1760E008;   // Message ID
sMsg.isExtended = TRUE; // Standard Message type
sMsg.isRtr = FALSE;     // Not RTR type
sMsg.dlc = 8;           // Length is 8 Bytes
sMsg.data[i++] = 0x18;  // Lower 4 Bytes
sMsg.data[i++] = 0x00;
sMsg.data[i++] = 0x84;
sMsg.data[i++] = 0x00;
sMsg.data[i++] = 0x00;
sMsg.data[i++] = 0x80;
sMsg.data[i++] = 0x00;
sMsg.data[i++] = 0x00;
sMsg.cluster = 1;
SendMsg(sMsg);
}/* End BUSMASTER generated function - Utils_cem_msg_send_150ms_1760E008 */
/* Start BUSMASTER generated function - Utils_cem_msg_send_200ms_19F010FC */
void Utils_cem_msg_send_200ms_19F010FC(void)
{
// Initialise message structure
STCAN_MSG sMsg;
unsigned char i = 0;

sMsg.id = 0x19F010FC;   // Message ID
sMsg.isExtended = TRUE; // Standard Message type
sMsg.isRtr = FALSE;     // Not RTR type
sMsg.dlc = 8;           // Length is 8 Bytes
sMsg.data[i++] = 0x98;//0x80;  // Lower 4 Bytes
sMsg.data[i++] = 0x00;
sMsg.data[i++] = 0x00;
sMsg.data[i++] = 0x40;
sMsg.data[i++] = 0x80;
sMsg.data[i++] = 0x00;
sMsg.data[i++] = 0xDE;//0x05;
sMsg.data[i++] = 0x26;//0x60;
sMsg.cluster = 1;
SendMsg(sMsg);
}/* End BUSMASTER generated function - Utils_cem_msg_send_200ms_19F010FC */
/* Start BUSMASTER generated function - Utils_cem_msg_send_200ms_1A621000 */
void Utils_cem_msg_send_200ms_1A621000(void)
{
// Initialise message structure
STCAN_MSG sMsg;
unsigned char i = 0;

sMsg.id = 0x1A621000;   // Message ID
sMsg.isExtended = TRUE; // Standard Message type
sMsg.isRtr = FALSE;     // Not RTR type
sMsg.dlc = 8;           // Length is 8 Bytes
sMsg.data[i++] = 0x00;  // Lower 4 Bytes
sMsg.data[i++] = 0x00;
sMsg.data[i++] = 0x00;
sMsg.data[i++] = 0x00;
sMsg.data[i++] = 0x00;
sMsg.data[i++] = 0x00;
sMsg.data[i++] = 0x00;
sMsg.data[i++] = 0x00;
sMsg.cluster = 1;
SendMsg(sMsg);
}/* End BUSMASTER generated function - Utils_cem_msg_send_200ms_1A621000 */
/* Start BUSMASTER generated function - Utils_cem_msg_send_300ms_1AD10068 */
void Utils_cem_msg_send_300ms_1AD10068(void)
{
// Initialise message structure
STCAN_MSG sMsg;
unsigned char i = 0;

sMsg.id = 0x1AD10068;   // Message ID
sMsg.isExtended = TRUE; // Standard Message type
sMsg.isRtr = FALSE;     // Not RTR type
sMsg.dlc = 8;           // Length is 8 Bytes
sMsg.data[i++] = 0x00;  // Lower 4 Bytes
sMsg.data[i++] = 0x04;
sMsg.data[i++] = 0x00;
sMsg.data[i++] = 0x00;
sMsg.data[i++] = (counter_100ms >> 24) & 0xFF;
sMsg.data[i++] = (counter_100ms >> 16) & 0xFF;
sMsg.data[i++] = (counter_100ms >> 8) & 0xFF;
sMsg.data[i++] = (counter_100ms >> 0) & 0xFF;
sMsg.cluster = 1;
SendMsg(sMsg);
}/* End BUSMASTER generated function - Utils_cem_msg_send_300ms_1AD10068 */
/* Start BUSMASTER generated function - Utils_cem_msg_send_360ms_1D604008 */
void Utils_cem_msg_send_360ms_1D604008(void)
{
// Initialise message structure
STCAN_MSG sMsg;
unsigned char i = 0;
static char j = 0;
char k = 0;

if(j>=7) j=0;

sMsg.id = 0x1D604008;   // Message ID
sMsg.isExtended = TRUE; // Standard Message type
sMsg.isRtr = FALSE;     // Not RTR type
sMsg.dlc = 8;           // Length is 8 Bytes
sMsg.data[i++] = 0x00;  // Lower 4 Bytes
sMsg.data[i++] = lut_1D604008[j][k++];
sMsg.data[i++] = lut_1D604008[j][k++];
sMsg.data[i++] = lut_1D604008[j][k++];
sMsg.data[i++] = lut_1D604008[j][k++];
sMsg.data[i++] = lut_1D604008[j][k++];
sMsg.data[i++] = lut_1D604008[j][k++];
sMsg.data[i++] = lut_1D604008[j++][k++];
sMsg.cluster = 1;
SendMsg(sMsg);
}/* End BUSMASTER generated function - Utils_cem_msg_send_360ms_1D604008 */
/* Start BUSMASTER generated function - Utils_cem_msg_send_250ms_1163F7FC */
void Utils_cem_msg_send_250ms_1163F7FC(void)
{
// Initialise message structure
STCAN_MSG sMsg;
unsigned char i = 0;
static char j = 0;
char k = 0;

if(j>=0x14) j = 0;

sMsg.id = 0x1163F7FC;   // Message ID
sMsg.isExtended = TRUE; // Standard Message type
sMsg.isRtr = FALSE;     // Not RTR type
sMsg.dlc = 8;           // Length is 8 Bytes
sMsg.data[i++] = j+1;    // Lower 4 Bytes
sMsg.data[i++] = lut_1163F7FC[j][k++];
sMsg.data[i++] = lut_1163F7FC[j][k++];
sMsg.data[i++] = lut_1163F7FC[j][k++];
sMsg.data[i++] = lut_1163F7FC[j][k++];
sMsg.data[i++] = lut_1163F7FC[j][k++];
sMsg.data[i++] = lut_1163F7FC[j][k++];
sMsg.data[i++] = lut_1163F7FC[j++][k++];
sMsg.cluster = 1;
SendMsg(sMsg);
}/* End BUSMASTER generated function - Utils_cem_msg_send_250ms_1163F7FC */
/* Start BUSMASTER generated function - Utils_cem_msg_send_500ms_1E30106A */
void Utils_cem_msg_send_500ms_1E30106A(void)
{
// Initialise message structure
STCAN_MSG sMsg;
unsigned char i = 0;

sMsg.id = 0x1E30106A;   // Message ID
sMsg.isExtended = TRUE; // Standard Message type
sMsg.isRtr = FALSE;     // Not RTR type
sMsg.dlc = 8;           // Length is 8 Bytes
sMsg.data[i++] = 0x40;  // Lower 4 Bytes
sMsg.data[i++] = 0x00;
sMsg.data[i++] = 0x00;
sMsg.data[i++] = 0x40;
sMsg.data[i++] = 0x40;
sMsg.data[i++] = 0x00;
sMsg.data[i++] = 0x00;
sMsg.data[i++] = 0x00;
sMsg.cluster = 1;
SendMsg(sMsg);
}/* End BUSMASTER generated function - Utils_cem_msg_send_500ms_1E30106A */
/* Start BUSMASTER generated function - Utils_cem_msg_send_500ms_1F600008 */
void Utils_cem_msg_send_500ms_1F600008(void)
{
// Initialise message structure
STCAN_MSG sMsg;
unsigned char i = 0;

sMsg.id = 0x1F600008;   // Message ID
sMsg.isExtended = TRUE; // Standard Message type
sMsg.isRtr = FALSE;     // Not RTR type
sMsg.dlc = 8;           // Length is 8 Bytes
sMsg.data[i++] = 0x00;  // Lower 4 Bytes
sMsg.data[i++] = 0x00;
sMsg.data[i++] = 0x00;
sMsg.data[i++] = 0x00;
sMsg.data[i++] = 0x40;
sMsg.data[i++] = 0x00;
sMsg.data[i++] = 0x00;
sMsg.data[i++] = 0x30;
sMsg.cluster = 1;
SendMsg(sMsg);
}/* End BUSMASTER generated function - Utils_cem_msg_send_500ms_1F600008 */
/* Start BUSMASTER generated function - OnTimer_timer12_250 */
void OnTimer_timer12_250( )
{
Utils_cem_msg_send_250ms_1093F7FC();
Utils_cem_msg_send_250ms_1163F7FC();
}/* End BUSMASTER generated function - OnTimer_timer12_250 */
/* Start BUSMASTER generated function - Utils_cem_msg_send_250ms_1093F7FC */
void Utils_cem_msg_send_250ms_1093F7FC(void)
{
// Initialise message structure
STCAN_MSG sMsg;
unsigned char i = 0;
static char j = 0;
char k = 1;
static char l = 1;

if(j>=12) { j=0; l=1;}

sMsg.id = 0x1093F7FC;   // Message ID
sMsg.isExtended = TRUE; // Standard Message type
sMsg.isRtr = FALSE;     // Not RTR type
sMsg.dlc = 8;           // Length is 8 Bytes
sMsg.data[i++] = lut_1093F7FC[j][k++];  // Lower 4 Bytes
sMsg.data[i++] = lut_1093F7FC[j][k++];
sMsg.data[i++] = lut_1093F7FC[j][k++];
sMsg.data[i++] = lut_1093F7FC[j][k++];
sMsg.data[i++] = lut_1093F7FC[j][k++];
sMsg.data[i++] = lut_1093F7FC[j][k++];
sMsg.data[i++] = lut_1093F7FC[j][k++];
sMsg.data[i++] = lut_1093F7FC[j][k++];

if(sMsg.data[0] == 0x01)
{
	i = 2;
	sMsg.data[i++] = (counter_100ms >> 24) & 0xFF;
	sMsg.data[i++] = (counter_100ms >> 16) & 0xFF;
	sMsg.data[i++] = (counter_100ms >> 8) & 0xFF;
	sMsg.data[i++] = (counter_100ms >> 0) & 0xFF;
}

sMsg.cluster = 1;

if(l==lut_1093F7FC[j][0])
{
	SendMsg(sMsg);
	j++;
}
l++;
}/* End BUSMASTER generated function - Utils_cem_msg_send_250ms_1093F7FC */
/* Start BUSMASTER generated function - OnDLL_Unload */
void OnDLL_Unload()
{
/* TODO */
}/* End BUSMASTER generated function - OnDLL_Unload */
/* Start BUSMASTER generated function - OnKey_p */
void OnKey_p(unsigned char KeyValue)
{
if(blinker_right != 0x30) blinker_right = 0x30;
else blinker_right = 0x20;
}/* End BUSMASTER generated function - OnKey_p */
/* Start BUSMASTER generated function - OnKey_o */
void OnKey_o(unsigned char KeyValue)
{
if(blinker_left != 0x28) blinker_left = 0x28;
else blinker_left = 0x20;
}/* End BUSMASTER generated function - OnKey_o */
/* Start BUSMASTER generated function - OnKey_m */
void OnKey_m(unsigned char KeyValue)
{
clock_m++;
if(clock_m>=60) {clock_m = 0; clock_h++;}
Trace("clock_m %d",clock_m);
}/* End BUSMASTER generated function - OnKey_m */
/* Start BUSMASTER generated function - OnKey_h */
void OnKey_h(unsigned char KeyValue)
{
clock_h++;
if(clock_h>=23) clock_h = 0;
Trace("clock_h %d",clock_h);
}/* End BUSMASTER generated function - OnKey_h */
/* Start BUSMASTER generated function - OnKey_b */
void OnKey_b(unsigned char KeyValue)
{
if(backlight==0xF)backlight = 0;
else backlight++;
Trace("Backlight: %02d [%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s]",
backlight,
(backlight>=0x1)?("*"):("_"),
(backlight>=0x2)?("*"):("_"),
(backlight>=0x3)?("*"):("_"),
(backlight>=0x4)?("*"):("_"),
(backlight>=0x5)?("*"):("_"),
(backlight>=0x6)?("*"):("_"),
(backlight>=0x7)?("*"):("_"),
(backlight>=0x8)?("*"):("_"),
(backlight>=0x9)?("*"):("_"),
(backlight>=0xA)?("*"):("_"),
(backlight>=0xB)?("*"):("_"),
(backlight>=0xC)?("*"):("_"),
(backlight>=0xD)?("*"):("_"),
(backlight>=0xE)?("*"):("_"),
(backlight>=0xF)?("*"):("_")
);
}/* End BUSMASTER generated function - OnKey_b */
/* Start BUSMASTER generated function - OnKey_t */
void OnKey_t(unsigned char KeyValue)
{
if(temp<0xDE)temp = 0xDE;
else if(temp==0xDE) temp++;
else temp-=2;
Trace("Temp %x",temp);
}/* End BUSMASTER generated function - OnKey_t */
